import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineGooglePlus,
  AiOutlinePhone,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/w22.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/1.png";
import web2 from "../public/2.png";
import web3 from "../public/3.png";
import web4 from "../public/4.png";
import web5 from "../public/6.png";
import web6 from "../public/7.webp";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>medhatjachour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-2 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbymga</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="./medhat_cv.pdf"
                  // download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center mb-12 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Medhat Ashour
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              SoftWare engineer.
            </h3>
            <p className="text-md py-3 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming. Join me down below
              and lets get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/medhatjachour?s=09" target="blank">
                {" "}
                <AiFillTwitterCircle />{" "}
              </a>
              <a
                href="https://www.linkedin.com/in/medhat-ashour-876a9518a/"
                target="blank"
              >
                {" "}
                <AiFillLinkedin />{" "}
              </a>
              <a href="https://github.com/medhatjachour" target="blank">
                {" "}
                <AiFillGithub />{" "}
              </a>
            </div>
            <div className="text-2xl  gap-16 py-3 text-gray-600 dark:text-gray-400">
              <p className=" flex justify-center gap-16ex">
                <AiOutlineGooglePlus className="text-6xl" />
                <span className="py-4 px-4"> Medhatashour19@gmail.com</span>
              </p>
     
              <p className=" flex justify-center gap-16ex"> 
                <AiOutlinePhone className="text-6xl" />
                <span className="py-4 px-4">+201015683986</span>
              </p>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-5 md:h-96 md:w-96">
              <Image
                src={deved}
                layout="fill"
                objectFit="cover"
                alt="my avatar"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Intro about me </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a motivated self-starter with the ability to quickly learn
              new technologies and develop creative solutions that meet customer
              needs. I enjoy working in a collaborative environment where team
              members can share ideas and work together to create the best
              possible product.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt = "front end"/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                web development
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Frontend</h4>
              <p className="text-gray-800 py-1">Html & Css</p>
              <p className="text-gray-800 py-1">JS</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">MUI</p>
              <p className="text-gray-800 py-1">Redux</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt = "backend" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                web development
              </h3>
              <p className="py-2">
              Designed and developed web applications across multiple APIs, third-party integrations and databases.
              </p>
              <h4 className="py-4 text-teal-600">Backend</h4>
              <p className="text-gray-800 py-1">ORM (sqlalchemy)</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Node</p>
              <p className="text-gray-800 py-1">Fastapi</p>
              <p className="text-gray-800 py-1">Sql (MySql, SqLite ..)</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="pyqt" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">DiskTop</h3>
              <p className="py-2">
                Build Responsive DiskTop application working on Windows ,macos and linux
              </p>
              <h4 className="py-4 text-teal-600">DiskTop</h4>
              <p className="text-gray-800 py-1">QT</p>
              <p className="text-gray-800 py-1">Qml</p>
              <p className="text-gray-800 py-1">PySide</p>
              <p className="text-gray-800 py-1">Electron</p>
              <p className="text-gray-800 py-1">Tkinter</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
              <p className="text-gray-800 py-0 max-h-2">.</p>
            </div>
            {/* <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <div className="skills-charts">
                <div id="myCanvasContainer">
                  <canvas width="500" height="500" id="myCanvas">
                    <ul id="tags">
                      <li>
                        <a href="#" target="_blank">
                          TypeScript
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          CSS
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          ES5
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          HTML
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          REST
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          JSON
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          PYQT
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          Data Science
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          Wordpress
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          FASTAPI
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          Python
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          Node JS
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          Git
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          THREE JS
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          SASS
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          JQuery
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          SQI
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          EXPRESS
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          npm
                        </a>
                      </li>
                      <li>
                        <a href="#" target="_blank">
                          BEM
                        </a>
                      </li>
                    </ul>
                  </canvas>
                </div>
              </div>
            </div> */}
          </div>
        </section>
 
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Feel free to navigate and check my public github repositories as there many examples for my previous work
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
